### PR TITLE
Fix overwritten export (#36) by adding a backwards compatible dist/hashids.js fallback file

### PR DESCRIPTION
**Pull request by niieani**
Updates babel to v7 and additionally adds support for ES modules under Node (.mjs).

### CODE REVIEW

**Comment by ivanakimov** [comment]
@niieani Thank you, this is great! Do you know what's up with https://travis-ci.org/ivanakimov/hashids.js/jobs/423206991 ?

Also, `in a backwards compatible way` -- does it work for frontend/backend/old/new? Anything to be aware of?

**Comment by niieani** [comment]
Ah, it seems babel's preset-env by default targets what's compatibile with Node >= 6. I can add a `browserslist` setting in package.json to list the minimum target, just let me know what combination of browsers/node versions you'd like to support in the `dist` version.

Any node version will use the `dist/index`, which behaves the same way as it did in the past. The minified version for use in the browser is the same as it used to be, though we should set the minimum target and a "browser" prop in package.json (I'll do that).

Then there's support for `.mjs` which is consumed by Node with experimental-modules flag and by Webpack 4.

We could probably drop the 0.xx versions of Node from Travis. As for Node v4, it's up to you.

**Comment by niieani** [comment]
I've dropped all unsupported Node versions (4 is no longer supported by the Node organization), if you deem that incorrect we can just adjust the setting in package.json and rebuild again. I've also added a "browser" prop to point to the minified version and added a "module" one for builders that support ES Modules, but don't support the `.mjs` extension.

**Comment by ivanakimov** [comment]
@niieani Many thanks for all the changes. I guess since maintenance cycle is over for v4, we can probably drop it. But we'd have to update either major or minor version, so devs are aware of the changes. Think you could update the changelog with your updates, and then I merge?

**Comment by ivanakimov** [comment]
Thank you @niieani. I updated the changelog since `1.1.5` was never released. Please let me know if you see something else that's funky.

**Comment by ivanakimov** [comment]
@niieani does the current code look release-ready to you?

**Comment by niieani** [comment]
@ivanakimov yeah, it looks fine.

**Comment by ivanakimov** [comment]
Thanks for all the changes @niieani :+1:
`1.2.0` published, cc @anisabboud

**Comment by niieani** [comment]
Works perfectly https://codesandbox.io/s/rmk16j6q8m
Thanks @ivanakimov!

**Comment by pierrefh** [comment]
Hi @ivanakimov I noticed a regression in my node.js (version 8 + babel) app since 1.2.1 (was previously 1.1.4): `_hashids2.default is not a constructor` when I import hashids.
```
import Hashids  from 'hashids'
const hashids = new Hashids('some salt', 10, HASHIDS_CHARS)
```

**Pull request merged**
