### PR TITLE
Fix importing via babel interop (fixes #56)

### LINKED ISSUE #56: TypeError in version 1.2.1
I just updated to the newest version and encountered this error:

`TypeError: Object is not a constructor (evaluating 'new Hashids()')`

### PR DESCRIPTION
**Pull request by niieani**
I apologize @ivanakimov, I didn't add tests for this initially as I thought I tested most cases manually. I've added 5 unit tests for different ways of requiring or importing the package and fixed the issue mentioned in #56.

Added a CHANGELOG too.

### CODE REVIEW

**Comment by ivanakimov** [comment]
@niieani no worries, A+ for following up. Do we need any more changes before I publish a new version?

**Comment by niieani** [comment]
@ivanakimov with all the tests now I think I've covered most common use cases, and we're unbreaking what is broken now, so I'd say: ready to publish.

**Comment by ivanakimov** [comment]
cool :) let's try again

**Pull request merged**
