### PR TITLE
fixed issue with sourceMappingURL in hashids.min.js

### PR DESCRIPTION
**Pull request by rdfriedl**
fixed the issue with `hashids.min.js` not correctly referencing `hashids.min.map`

this was causing webpack to output a warning when `hashids` was part of the bundle

```
WARNING in ./node_modules/source-map-loader!./node_modules/hashids/dist/hashids.min.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'dist/hashids.min.map': Error: Can't resolve './dist/hashids.min.map' in '/<project-path>/node_modules/hashids/dist'
 @ ./node_modules/hashids/dist/hashids.min.js 1:37-146
 @ ./app/index.js
```
*the `<project-path>` is the absolute path to the project

### CODE REVIEW

**Comment by rdfriedl** [comment]
@ivanakimov could you look over this real quick?
its nothing critical but id really like to get this issue fixed so that webpack will stop putting out warnings.

Thanks :)

**Comment by ivanakimov** [comment]
Thanks for the PR and the ping @rdfriedl. It looks like your `dist/hashids.js` differs from mine when I try your minify, so I am guessing you're using a different dependency version somewhere.

So to keep things simple, I'm just going to push that same change from my end. Hang tight.

**Comment by ivanakimov** [comment]
Ahhh cool. Got same results as you now from a fresh npm install. Nevermind.

**Comment by rdfriedl** [comment]
@ivanakimov awesome thanks.
and yes, i think when i installed the dependencies it installed a newer version of babel.

if you use `npm 5` or `yarn` i would commit the `yarn.lock` or the `packet-lock.json` file, that should keep the dependencies at the correct versions when someone installs :smile:

**Comment by ivanakimov** [comment]
@rdfriedl try `1.1.2`

**Comment by rdfriedl** [comment]
@ivanakimov awesome works perfectly now :+1: no warnings and the source shows up in the chrome  inspector

**Pull request merged**
